# Generated by Django 3.2.3 on 2021-08-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('Admin', 'Admin'), ('Cliente', 'Cliente'), ('Vendedor', 'Vendedor')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=55)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rol', to='gasbravo.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dir', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_log', to='gasbravo.user')),
            ],
        ),
    ]
