# Generated by Django 3.2.3 on 2021-08-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasbravo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('dire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasbravo.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Status_Ped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('ped_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasbravo.pedido')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasbravo.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='ped_prod',
            field=models.ManyToManyField(through='gasbravo.Pedido_prod', to='gasbravo.Producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasbravo.status_ped'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasbravo.user'),
        ),
    ]
