# Generated by Django 3.2.3 on 2021-08-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasbravo', '0002_auto_20210811_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='cantidad_stock',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='bodega',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, null=True),
        ),
    ]
