# Generated by Django 3.2.3 on 2021-08-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasbravo', '0005_alter_producto_precio_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='guia_rem',
            new_name='factura',
        ),
        migrations.AddField(
            model_name='bodega',
            name='proveedor',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
