# Generated by Django 3.2.3 on 2021-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasbravo', '0006_auto_20210814_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='factura',
            field=models.CharField(max_length=15),
        ),
    ]
