# Generated by Django 3.2.3 on 2021-08-15 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasbravo', '0007_alter_bodega_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_ped',
            name='status',
        ),
        migrations.AddField(
            model_name='status_ped',
            name='estados',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='prod_bod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_emailUSER_ROLbod', to='gasbravo.producto'),
        ),
    ]
