# Generated by Django 3.2.3 on 2021-08-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasbravo', '0007_alter_bodega_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
