# Generated by Django 3.2.3 on 2021-08-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasbravo', '0008_auto_20210814_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cedula',
            field=models.CharField(default='9999999999', max_length=15),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(default='Consumidor Final', max_length=250),
        ),
        migrations.AddField(
            model_name='pedido',
            name='correo',
            field=models.CharField(default='facturaciongas@gmail.com', max_length=250),
        ),
        migrations.AddField(
            model_name='pedido',
            name='iva_pedido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal_pedido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido_prod',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='prod_bod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_bod', to='gasbravo.producto'),
        ),
    ]
