# Generated by Django 3.2.3 on 2021-08-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasbravo', '0010_alter_pedido_dire_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='stat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_id', to='gasbravo.status_ped'),
        ),
    ]
