# Generated by Django 3.2.3 on 2021-08-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasbravo', '0013_alter_pedido_usr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_prod',
            name='ped_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ped_id', to='gasbravo.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido_prod',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_id', to='gasbravo.producto'),
        ),
    ]
