# Generated by Django 3.2.3 on 2021-08-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasbravo', '0008_alter_bodega_precio_compra'),
        ('gasbravo', '0015_remove_pedido_ped_prod'),
    ]

    operations = [
    ]
